name: parkour_spot
description: "A Flutter app for reporting and discovering parkour spots."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  cloud_functions: ^6.0.5
  
  # State Management
  provider: ^6.1.2
  
  # UI Components
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  google_fonts: ^7.0.0
  google_maps_flutter: ^2.12.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  cached_network_image_platform_interface: ^4.1.1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  photo_view: ^0.15.0
  
  # Location & Maps
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  
  # Utilities
  http: ^1.2.2
  uuid: ^4.5.1
  intl: ^0.20.2
  sealed_countries: ^2.0.0
  country_flags: ^4.1.1
  image: ^4.3.0
  heic_to_png_jpg: ^0.0.6
  
  # Deep Linking & Navigation
  url_launcher: ^6.3.1
  go_router: ^17.0.1
  
  # Web
  web: ^1.1.0
  flutter_web_plugins:
    sdk: flutter
  shared_preferences: ^2.2.3
  webview_flutter: ^4.2.4
  webview_flutter_web: ^0.2.3+4
  pointer_interceptor: ^0.10.1
  validators: ^3.0.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/