// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8DOQMB0A4e0e5cT-csqjaLi_BrDK7FmQ',
    appId: '1:999200005209:web:ff17ea851ea892a8926548',
    messagingSenderId: '999200005209',
    projectId: 'parkourspot-93c90',
    authDomain: 'parkourspot-93c90.firebaseapp.com',
    storageBucket: 'parkourspot-93c90.firebasestorage.app',
    measurementId: 'G-861J61HFR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8DOQMB0A4e0e5cT-csqjaLi_BrDK7FmQ',
    appId: '1:999200005209:android:ff17ea851ea892a8926548',
    messagingSenderId: '999200005209',
    projectId: 'parkourspot-93c90',
    storageBucket: 'parkourspot-93c90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8DOQMB0A4e0e5cT-csqjaLi_BrDK7FmQ',
    appId: '1:999200005209:ios:ff17ea851ea892a8926548',
    messagingSenderId: '999200005209',
    projectId: 'parkourspot-93c90',
    storageBucket: 'parkourspot-93c90.firebasestorage.app',
    iosBundleId: 'com.example.parkourSpot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8DOQMB0A4e0e5cT-csqjaLi_BrDK7FmQ',
    appId: '1:999200005209:macos:ff17ea851ea892a8926548',
    messagingSenderId: '999200005209',
    projectId: 'parkourspot-93c90',
    storageBucket: 'parkourspot-93c90.firebasestorage.app',
    iosBundleId: 'com.example.parkourSpot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8DOQMB0A4e0e5cT-csqjaLi_BrDK7FmQ',
    appId: '1:999200005209:windows:ff17ea851ea892a8926548',
    messagingSenderId: '999200005209',
    projectId: 'parkourspot-93c90',
    storageBucket: 'parkourspot-93c90.firebasestorage.app',
  );
}
